Migrate the CLI to v2 of the golang sdk
aws/amazon-ec2-instance-selector pull request #158
Opened 2022-09-21 16:08 UTC by wilsonge

Description of changes:

- Initial work on migrating the app to version 2 of the SDK. Obviously this would be a new major version of the product.

Current progress: App has largely been migrated to the new SDK's with equivalent functionality. Some functionality has been dropped relating to the injection of regions from different sources. Additionally there's still a hard dependency on the v1 sdk endpoints package which will likely require some work on the smithy side of things to generate a mapping between regions and descriptions (it's in the smithy generated json file but not in the golang sdk). Tests are still a WIP and some more minor restructuring will likely be required as part of that. However this gets this into the wild for initial reviews.

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2022-10-06 19:36 UTC, bwagner5 commented
Hey! Thanks for working on this! Curious what the binary size diff was on the WIP for this PR? Seems valuable to do anyways to support clients using v2 versus v1. I suppose if a client is using v1 though, this change would pull in the additional v2 deps for their binary (I think kOps uses v1). I would guess the binary sizes wouldn't be radically different though since the unused packages would shaken out during compilation.

2022-10-10 16:06 UTC, wilsonge commented
Interestingly bigger. Looks like the ec2 serializers are pretty hefty https://github.com/aws/aws-sdk-go-v2/blob/main/service/ec2/serializers.go about 60k lines :) about 33MB for now - but 3MB of that is the v1 package endpoints - which like I say can probably be removed in favour of smithy generated stuff.

I've committed fixes for the last 2 tests (at least they pass now locally). Would be good to get a retrigger on the tests here to see if they pass on the git workflows

2022-10-11 14:33 UTC, snay2 commented
@wilsonge We've been maintaining the `THIRD_PARTY_LICENSES` file by hand. You can copy/paste and follow the same formatting for any new libraries.

2022-10-18 10:55 UTC, wilsonge commented
@snay2 / @bwagner5 sorry to be a pain but could i get you to retrigger the workflow please

2022-10-20 13:52 UTC, wilsonge commented
OK So tests here look good. What's the next steps. I think this one needs some proper human code review too because there's an awful lot of changes.

2022-10-20 14:50 UTC, snay2 commented
@wilsonge Have you finished the tasks you outlined in the PR description? If so, I'd say check those off and remove "draft" from the title, and we'll start reviewing the code.

2022-12-01 15:53 UTC, cjerad requested changes
Hi wilsonge, in addition to the outstanding tasks I have a few questions and suggestions.

2023-03-14 08:14 UTC, TiberiuGC commented
Hi 👋 - reaching out on eksctl behalf, we're also looking forward to completely migrate to go sdk v2. Is there any chance the work on this PR will be picked up from where it was left in the foreseeable future?

2023-03-15 16:53 UTC, jillmon commented
hi @TiberiuGC. I wasn't aware that eksctl had a dependency on EC2 Instance Selector. Can you give us more detail as to how you're utilizing this tool. It would help with our prioritization of this PR because it looks like this may require another developer to pick up where @wilsonge has left off.

2023-03-15 18:25 UTC, TiberiuGC commented
@jillmon when creating (clusters with) nodegroups using eksctl, users have the option to specify the properties they want for their nodes e.g.
```
eksctl create nodegroup --instance-selector-
--instance-selector-cpu-architecture  -- x86_64, or arm64
--instance-selector-gpus              -- an integer value
--instance-selector-memory            -- 4 or 4GiB
--instance-selector-vcpus             -- an integer value (2, 4 etc)
```
and we let instance selector do it's magic on deciding the instance types.

As to why this PR is relevant for us, I think @wilsonge explained it well in the description

> **Why Migrate to V2**
...
Some projects that depend on this (e.g. eksctl) are currently having to create two sessions - one in the v2 sdk for all their direct dependencies and one in the v1 sdk for this project. 

Let me know if I can provide any more info 🙏

2023-03-20 23:16 UTC, wilsonge commented on pkg/ec2pricing/ec2pricing.go
> +	}
Done but worth noting the function currently doesn't return an error so makes the b/c impact larger

2023-03-21 11:32 UTC, wilsonge commented on pkg/awsapi/instancetypesec2.go
> +}
No clue :D I added them in for testing at some point but no clue why anymore. Removed again :)

2023-03-21 11:57 UTC, wilsonge commented on cmd/main.go
> +		CPUManufacturer:                  &cpuManufacturerFilterValue,
Correct but my assumption (rightly or wrongly) was that this sort of stuff would bubble up in the integration tests you guys have. I don't think there's any easy workaround - it's a fallout of the stricter type definitions in the new sdk.

2023-03-21 11:58 UTC, wilsonge commented
I've rebased this onto the latest main branch and applied most the review comments. There's still my todo's listed above (on me but if someone else wants to pick them up as I don't have huge amounts of time just let me know) and the outstanding item about the region lists which I still believe needs an AWS staff member to be resolved.

2023-05-03 19:32 UTC, cjerad requested changes
Hi wilsonge, thanks for updating this. Just a few small suggestions.

2023-05-03 19:32 UTC, cjerad commented on pkg/ec2pricing/odpricing.go
> +	_ = os.Mkdir(c.DirectoryPath, 0755)
Please handle error

2023-05-03 19:32 UTC, cjerad commented on pkg/ec2pricing/odpricing.go
> +		_ = odPricing.Clear()
Please handle error

2023-05-05 23:35 UTC, wilsonge commented on cmd/main.go
> +	ctx := context.Background()
This is to allow us to remove the registerShutdown line in this file in a more native way? Just for my understanding

2023-05-05 23:42 UTC, wilsonge commented on pkg/selector/selector.go
> +		filters, err = transform.Transform(ctx, filters)
Not sure now. Guess it wasn't :)

2023-05-05 23:53 UTC, wilsonge commented on cmd/main.go
> +		CPUManufacturer:                  &cpuManufacturerFilterValue,
Implemented :)

2023-05-05 23:54 UTC, wilsonge commented
Pushed up the latest changes requested. I've also pushed a change to better handle the aws context usage for the pricing client that will need a quick review on top of the previous stuff.

2023-05-24 15:12 UTC, cjerad requested changes

2023-06-01 19:09 UTC, cjerad commented
Resolved merge conflicts locally then squashed and pushed all changes.

2023-06-01 19:09 UTC, closed without merging