Add Spot/On-demand price to table-wide output irrespective of the price filters
aws/amazon-ec2-instance-selector pull request #78
Opened 2021-03-06 05:08 UTC by krishna-birla

## Side effects:
* Minor clean-up
* Update `.gitignore`
* Add dependency `go.uber.org/multierr v1.1.0`

## Issue, if available:
#71 

## Description of changes:
To show Spot and On Demand prices in table wide output irrespective of the price filters being set; if the filters are set, do filtration normally depending on usage class. For other output modes, do filtration normally depending on usage class.

## Testing:
#### Table wide output - us-east-1 (both cache was hydrated)
```
Krishna-Birla:amazon-ec2-instance-selector krishna.birla$ ./build/ec2-instance-selector -o table-wide --region us-east-1 --max-results 10
Instance Type  VCPUs   Mem (GiB)  Hypervisor  Current Gen  Hibernation Support  CPU Arch      Network Performance  ENIs    GPUs    GPU Mem (GiB)  GPU Info  On-Demand Price/Hr  Spot Price/Hr (30d avg)
-------------  -----   ---------  ----------  -----------  -------------------  --------      -------------------  ----    ----    -------------  --------  ------------------  -----------------------
a1.2xlarge     8       16         nitro       false        false                arm64         Up to 10 Gigabit     4       0       0                        $0.204              $0.06769
a1.4xlarge     16      32         nitro       false        false                arm64         Up to 10 Gigabit     8       0       0                        $0.408              $0.1343
a1.large       2       4          nitro       false        false                arm64         Up to 10 Gigabit     3       0       0                        $0.051              $0.01694
a1.medium      1       2          nitro       false        false                arm64         Up to 10 Gigabit     2       0       0                        $0.0255             $0.0084
a1.metal       16      32         none        false        false                arm64         Up to 10 Gigabit     8       0       0                        $0.408              $0.1343
a1.xlarge      4       8          nitro       false        false                arm64         Up to 10 Gigabit     4       0       0                        $0.102              $0.0336
c1.medium      2       1.69922    xen         false        false                i386, x86_64  Moderate             2       0       0                        $0.13               $0.01402
c1.xlarge      8       7          xen         false        false                x86_64        High                 4       0       0                        $0.52               $0.11083
c3.2xlarge     8       15         xen         false        true                 x86_64        High                 4       0       0                        $0.42               $0.13062
c3.4xlarge     16      30         xen         false        true                 x86_64        High                 8       0       0                        $0.84               $0.31342
NOTE: 373 entries were truncated, increase --max-results to see more
```
#### Table wide output - ap-south-1 (both cache was hydrated)
```
Krishna-Birla:amazon-ec2-instance-selector krishna.birla$ ./build/ec2-instance-selector -o table-wide --region ap-south-1 --max-results 10
Instance Type  VCPUs   Mem (GiB)  Hypervisor  Current Gen  Hibernation Support  CPU Arch  Network Performance  ENIs    GPUs    GPU Mem (GiB)  GPU Info  On-Demand Price/Hr  Spot Price/Hr (30d avg)
-------------  -----   ---------  ----------  -----------  -------------------  --------  -------------------  ----    ----    -------------  --------  ------------------  -----------------------
a1.2xlarge     8       16         nitro       false        false                arm64     Up to 10 Gigabit     4       0       0                        $0.204              $0.0547
a1.4xlarge     16      32         nitro       false        false                arm64     Up to 10 Gigabit     8       0       0                        $0.408              $0.1095
a1.large       2       4          nitro       false        false                arm64     Up to 10 Gigabit     3       0       0                        $0.051              $0.0137
a1.medium      1       2          nitro       false        false                arm64     Up to 10 Gigabit     2       0       0                        $0.0255             $0.0068
a1.metal       16      32         none        false        false                arm64     Up to 10 Gigabit     8       0       0                        $0.408              $0.1095
a1.xlarge      4       8          nitro       false        false                arm64     Up to 10 Gigabit     4       0       0                        $0.102              $0.0274
c4.2xlarge     8       15         xen         true         true                 x86_64    High                 4       0       0                        $0.4                $0.12467
c4.4xlarge     16      30         xen         true         true                 x86_64    High                 8       0       0                        $0.8                $0.20867
c4.8xlarge     36      60         xen         true         true                 x86_64    10 Gigabit           8       0       0                        $1.6                $0.42315
c4.large       2       3.75       xen         true         true                 x86_64    Moderate             3       0       0                        $0.1                $0.02553
NOTE: 226 entries were truncated, increase --max-results to see more
```
#### Table output - ap-south-1 (both cache was NOT hydrated)
```
Krishna-Birla:amazon-ec2-instance-selector krishna.birla$ ./build/ec2-instance-selector -o table --region ap-south-1 --max-results 10
Instance Type        VCPUs        Mem (GiB)
-------------        -----        ---------
a1.2xlarge           8            16
a1.4xlarge           16           32
a1.large             2            4
a1.medium            1            2
a1.metal             16           32
a1.xlarge            4            8
c4.2xlarge           8            15
c4.4xlarge           16           30
c4.8xlarge           36           60
c4.large             2            3.75
NOTE: 226 entries were truncated, increase --max-results to see more
```
#### Table wide output with price filter - ap-south-1 (both cache was hydrated)
```
Krishna-Birla:amazon-ec2-instance-selector krishna.birla$ ./build/ec2-instance-selector -o table-wide --region ap-south-1 --max-results 10 --price-per-hour 0.0255
Instance Type  VCPUs   Mem (GiB)  Hypervisor  Current Gen  Hibernation Support  CPU Arch  Network Performance  ENIs    GPUs    GPU Mem (GiB)  GPU Info  On-Demand Price/Hr  Spot Price/Hr (30d avg)
-------------  -----   ---------  ----------  -----------  -------------------  --------  -------------------  ----    ----    -------------  --------  ------------------  -----------------------
a1.medium      1       2          nitro       false        false                arm64     Up to 10 Gigabit     2       0       0                        $0.0255             $0.0068
```
#### Table wide output with price filter and usage class - ap-south-1 (both cache was hydrated)
```
Krishna-Birla:amazon-ec2-instance-selector krishna.birla$ ./build/ec2-instance-selector -o table-wide --region ap-south-1 --max-results 10 --price-per-hour 0.0068 --usage-class spot
Instance Type  VCPUs   Mem (GiB)  Hypervisor  Current Gen  Hibernation Support  CPU Arch  Network Performance  ENIs    GPUs    GPU Mem (GiB)  GPU Info  On-Demand Price/Hr  Spot Price/Hr (30d avg)
-------------  -----   ---------  ----------  -----------  -------------------  --------  -------------------  ----    ----    -------------  --------  ------------------  -----------------------
a1.medium      1       2          nitro       false        false                arm64     Up to 10 Gigabit     2       0       0                        $0.0255             $0.0068
```
#### Table wide output with price range filter - ap-south-1 (both cache was hydrated)
```
Krishna-Birla:amazon-ec2-instance-selector krishna.birla$ ./build/ec2-instance-selec [...]

2021-03-07 21:07 UTC, bwagner5 requested changes
Overall very nice refactor and thanks for contributing to this project!! I've left a few minor comments in-line.  

It looks like the unit-tests are also failing.  There's some test coverage missing on the output, selector, and ec2-pricing pkgs too. Would you mind upping the coverage for those packages for this enhancement? 

I commented about how to fix the pricing endpoint, no obligation for you fix it, but if you'd like to include that fix or open a new PR, feel free. If not, I'll fix that sometime this week. 

Thanks again!

2021-03-07 21:07 UTC, bwagner5 commented on pkg/selector/selector.go
> +	var locations, aZones []string
can we call `aZones` one of these instead: `zones`, `availabilityZones`, `azs`?

2021-03-23 15:29 UTC, bwagner5 commented
Hey @krishna-birla , just wanted to check in and see if there's anything I can help with to get this merged?  No worries if you've just been busy!

2021-03-23 17:30 UTC, krishna-birla commented
> Hey @krishna-birla , just wanted to check in and see if there's anything I can help with to get this merged? No worries if you've just been busy!

Unfortunately it is the later, typical end of quarter. Anyway, will dedicate this week to it.

When do you plan to release?

2021-03-23 17:31 UTC, krishna-birla commented on pkg/ec2pricing/ec2pricing.go
> +	"github.com/aws/aws-sdk-go/service/lightsail"
My bad.

2021-03-23 17:31 UTC, krishna-birla commented on pkg/ec2pricing/ec2pricing.go
> +	"github.com/aws/aws-sdk-go/aws/endpoints"
Sure. Will add that to my fmt rules for this project.

2021-03-23 17:31 UTC, krishna-birla commented on pkg/ec2pricing/ec2pricing.go
> +	LastOnDemandCachedUTC() *time.Time
Okie.

2021-03-26 19:54 UTC, bwagner5 commented
I'm in no rush, take your time and let me know if you need any help! :)

2021-04-29 15:50 UTC, bwagner5 commented
Hey, just checking in. If you won't have the time to work on this soon, I could merge this PR and then I could work on a follow up to address some of the comments in this PR. Would that be okay with you?

2021-04-30 09:07 UTC, krishna-birla commented
The UTs need changes. I hit a roadblock with just one thing: internal function to get price does not know when it was called by CLI (i.e. via main function) and when it was called directly by SDK. Because for SDK callers, we don't cache but want to report prices all the same. And so I was trying to make internal function aware of this, which is what I was trying with "LastCachedUTC()" function. This is what I was working on last around 3 weeks ago, but I was tested covid +ve and had to halt with it 😅.

I don't know if we can merge this as is, as tests are failing and some finishing is required.

If you want you can close this (and I will re-open it when I am able to) and mean while submit the much smaller fix for ```To fix https://docs.aws.amazon.com/awsaccountbilling/latest/aboutv2/using-pelong.html#pe-endpoint , I believe we can just copy the session and change the region to always use us-east-1 just for the PricingClient. The filters already include the location. I didn't realize pricing was a global endpoint :) I can do this fix if you'd like.``` this issue.

2021-04-30 09:08 UTC, krishna-birla commented
I may get some time this weekend, or next week to find a good solution for "LastCachedUTC()" stuff. 🤞🏽

2021-04-30 09:10 UTC, krishna-birla commented
I just saw this: https://github.com/aws/amazon-ec2-instance-selector/issues/84#issuecomment-829354174. I'll try to prioritise.

2021-05-05 22:32 UTC, bwagner5 commented
Made the pricing client endpoint change here: https://github.com/aws/amazon-ec2-instance-selector/pull/85

2021-11-15 16:08 UTC, bwagner5 commented
Finished in https://github.com/aws/amazon-ec2-instance-selector/pull/106 

Thanks for the collab on this @krishna-birla !

2021-11-15 16:08 UTC, closed without merging